#region

using System.ComponentModel.DataAnnotations;
using HimuOJ.Common.WebHostDefaults.Extensions;

#endregion

namespace HimuOJ.Services.Problems.Domain.AggregatesModel.ProblemAggregate;

/// <summary>
///     The <see cref="Problem" /> is the basic unit for users to submit test.
/// </summary>
public class Problem : Entity, IAggregateRoot
{
    private readonly List<TestPoint> _testPoints;

    protected Problem()
    {
        _testPoints = new List<TestPoint>();
    }

    public Problem(
        Guid? distributorId,
        string title,
        string content,
        ResourceLimit resourceLimit,
        GuestAccessLimit guestAccessLimit)
        : this()
    {
        DistributorId        = distributorId;
        Title                = title;
        Content              = content;
        CreateTime           = DateTime.UtcNow;
        LastModifyTime       = DateTime.UtcNow;
        DefaultResourceLimit = resourceLimit;
        GuestAccessLimit     = guestAccessLimit;
    }

    public Guid? DistributorId { get; private set; }

    [Required]
    public string Title { get; private set; }

    /// <summary>
    ///     Content should be MarkDown format.
    /// </summary>
    [Required]
    public string Content { get; private set; }

    public DateTime CreateTime { get; private set; }

    public DateTime LastModifyTime { get; private set; }

    /// <summary>
    ///     The default resource limit for each test point in this problem.
    /// </summary>
    [Required]
    public ResourceLimit DefaultResourceLimit { get; private set; }

    [Required]
    public GuestAccessLimit GuestAccessLimit { get; private set; }

    public IReadOnlyCollection<TestPoint> TestPoints => _testPoints.AsReadOnly();

    public void Update(
        string title,
        string content,
        ResourceLimit resourceLimit,
        GuestAccessLimit guestAccessLimit,
        IEnumerable<TestPoint> testPointsUpdated)
    {
        Title                = title;
        Content              = content;
        DefaultResourceLimit = resourceLimit;
        GuestAccessLimit     = guestAccessLimit;
        LastModifyTime       = DateTime.UtcNow;

        var intersection = testPointsUpdated
            .IntersectWithDifference(_testPoints, out var testPointsAdded)
            .ToHashSet();
        var currentTestPoints = _testPoints.ToList();
        for (int i = 0; i < currentTestPoints.Count; i++)
        {
            bool found = intersection.TryGetValue(currentTestPoints[i], out var testPointToUpdate);
            if (found)
            {
                _testPoints[i]
                    .Update(
                        testPointToUpdate.Input,
                        testPointToUpdate.ExpectedOutput,
                        testPointToUpdate.Remarks);
            }
            else
            {
                _testPoints.Remove(currentTestPoints[i]);
            }
        }

        foreach (var testPoint in testPointsAdded)
        {
            _testPoints.Add(testPoint);
        }
    }

    public void AddTestPoint(string input, string expectedOutput, string remarks)
    {
        // ID will be generated by EF Core.
        _testPoints.Add(new TestPoint(0, Id, input, expectedOutput, remarks));
    }
}