/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManage: typeof import('./src/components/users/AccountManage.vue')['default']
    AvatarWithText: typeof import('./src/components/shared/AvatarWithText.vue')['default']
    CenterContentContainer: typeof import('./src/components/shared/CenterContentContainer.vue')['default']
    GuestAccessLimitTag: typeof import('./src/components/problems/GuestAccessLimitTag.vue')['default']
    HimuBackground: typeof import('./src/components/shared/HimuBackground.vue')['default']
    HimuCopyright: typeof import('./src/components/shared/HimuCopyright.vue')['default']
    HimuNavBar: typeof import('./src/components/shared/HimuNavBar.vue')['default']
    ListGotoItem: typeof import('./src/components/shared/ListGotoItem.vue')['default']
    MockAuthPanel: typeof import('./src/components/dev/MockAuthPanel.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    ProblemCommitTabs: typeof import('./src/components/problems/ProblemCommitTabs.vue')['default']
    ProblemDetailPreview: typeof import('./src/components/problems/ProblemDetailPreview.vue')['default']
    ProblemList: typeof import('./src/components/problems/ProblemList.vue')['default']
    ProblemManageList: typeof import('./src/components/problems/ProblemManageList.vue')['default']
    ProblemsManage: typeof import('./src/components/users/ProblemsManage.vue')['default']
    ResourceLimitTag: typeof import('./src/components/problems/ResourceLimitTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmissionList: typeof import('./src/components/submissions/SubmissionList.vue')['default']
    SubmissionRemarks: typeof import('./src/components/submissions/SubmissionRemarks.vue')['default']
    SubmissionStatusTag: typeof import('./src/components/submissions/SubmissionStatusTag.vue')['default']
    TestPointResult: typeof import('./src/components/submissions/TestPointResult.vue')['default']
  }
}
