/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManage: typeof import('./src/components/users/AccountManage.vue')['default']
    AvatarWithText: typeof import('./src/components/shared/AvatarWithText.vue')['default']
    CenterContentContainer: typeof import('./src/components/shared/CenterContentContainer.vue')['default']
    CommitList: typeof import('./src/components/commits/CommitList.vue')['default']
    CommitResultCard: typeof import('./src/components/commits/CommitResultCard.vue')['default']
    Commits: typeof import('./src/components/profile/Commits.vue')['default']
    ContentWithSideBar: typeof import('./src/components/ContentWithSideBar.vue')['default']
    ContestList: typeof import('./src/components/contests/ContestList.vue')['default']
    GuestAccessLimitLabel: typeof import('./src/components/problems/GuestAccessLimitLabel.vue')['default']
    GuestAccessLimitTag: typeof import('./src/components/problems/GuestAccessLimitTag.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HimuBackground: typeof import('./src/components/shared/HimuBackground.vue')['default']
    HimuCopyright: typeof import('./src/components/shared/HimuCopyright.vue')['default']
    HimuNavBar: typeof import('./src/components/shared/HimuNavBar.vue')['default']
    HvrIconButton: typeof import('./src/components/HvrIconButton.vue')['default']
    Info: typeof import('./src/components/profile/Info.vue')['default']
    ListGotoItem: typeof import('./src/components/shared/ListGotoItem.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCol: typeof import('naive-ui')['NCol']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NText: typeof import('naive-ui')['NText']
    ProblemCommitTabs: typeof import('./src/components/problems/ProblemCommitTabs.vue')['default']
    ProblemDetailPreview: typeof import('./src/components/problems/ProblemDetailPreview.vue')['default']
    ProblemList: typeof import('./src/components/problems/ProblemList.vue')['default']
    ProblemManageList: typeof import('./src/components/problems/ProblemManageList.vue')['default']
    ProblemsManage: typeof import('./src/components/users/ProblemsManage.vue')['default']
    PublishManage: typeof import('./src/components/profile/PublishManage.vue')['default']
    Register: typeof import('./src/components/users/Register.vue')['default']
    ResourceLimitTag: typeof import('./src/components/problems/ResourceLimitTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunResultPointDetail: typeof import('./src/components/RunResultPointDetail.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    SubmissionList: typeof import('./src/components/submissions/SubmissionList.vue')['default']
    SubmissionRemarks: typeof import('./src/components/submissions/SubmissionRemarks.vue')['default']
    SubmissionStatusTag: typeof import('./src/components/submissions/SubmissionStatusTag.vue')['default']
    TestPointResult: typeof import('./src/components/submissions/TestPointResult.vue')['default']
  }
}
